"""The world's records, typed and frozen: the logic's (written in logic/) and the data files' (data_tables.py)."""
from __future__ import annotations

from dataclasses import dataclass, fields
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from rule_builder.rules import Rule

GAME = "Bug Fables"


def _known(cls: type, data: dict[str, Any]) -> dict[str, Any]:
    """The entry's fields, refusing a key the record doesn't have (a typo would otherwise be ignored)."""
    names = {field.name for field in fields(cls)}
    unknown = set(data) - names - {"_comment"}
    if unknown:
        raise ValueError(f"bug_fables: {cls.__name__} {data.get('name', '')!r} has unknown keys {sorted(unknown)}")
    return {key: value for key, value in data.items() if key in names}


@dataclass(frozen=True, slots=True, kw_only=True)
class Item:
    """An item this world can place (data/items.json).

    game_id is the MainManager.Items ordinal (the enum starts at None = -1). kind is where it goes:
    0 ordinary items, 1 key items, 2 medals (game_id is the medal id, MainManager.BadgeTypes), 3 berries (money;
    game_id is the amount), 4 crystal berries (one item, game_id 0; the count is the currency; filler until the crystal
    berry shop is in the seed, then progression, since they buy locations there), 5 party members (game_id 0 Vi,
    1 Kabbu, 2 Leif), 6 field abilities (game_id 0 Progressive Beemerang, 1 Horn Slash, 2 Progressive Freeze, 3 Jump,
    4 Progressive Dash, 5 Bee Fly, 6 Beetle Dig, 7 Shield; their names and copies are in abilities.py).

    The Archipelago id is ITEM_ID_BASE + game_id, plus MEDAL_ID_OFFSET for a medal (medal ids overlap item ids),
    MONEY_ID_OFFSET for berries, CRYSTAL_ID_OFFSET for crystal berries, MEMBER_ID_OFFSET for a party member or
    MOVE_ID_OFFSET for a field move.

    padding: the filler used to fill leftover locations, in any number. always: enters the pool once in every seed,
    taking a filler slot (the mod's own items, which no location holds in vanilla). member: a party member, in the
    pool only with Starting Party Member on (the two not starting). move: a field ability's item, in the pool as many
    times as abilities.py says. Every other item enters the pool once per included location that holds it in vanilla.
    """

    name: str
    game_id: int
    kind: int
    classification: str
    padding: bool = False
    always: bool = False
    member: bool = False
    move: bool = False

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Item:
        return cls(**_known(cls, data))


@dataclass(frozen=True, slots=True, kw_only=True)
class Encounter:
    """A map enemy and the fight it starts (data/enemies.json, generated by dev-scripts/enemy-table.py).

    map and entity: the map and the enemy's entity index there. ids: the enemy ids its fight starts with.
    respawns: a puzzle enemy that comes back after a while (its map model must stay).
    """

    map: str
    entity: int
    ids: tuple[int, ...]
    respawns: bool

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Encounter:
        known = _known(cls, data)
        return cls(**{**known, "ids": tuple(known["ids"])})


@dataclass(frozen=True, slots=True, kw_only=True)
class DoorEnd:
    """One side of a door connection: the map and the door entity's name."""

    map: str
    door: str

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> DoorEnd:
        return cls(**_known(cls, data))


@dataclass(frozen=True, slots=True, kw_only=True)
class DoorConnection:
    """Two doors that lead into each other in the vanilla game."""

    a: DoorEnd
    b: DoorEnd

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> DoorConnection:
        known = _known(cls, data)
        return cls(a=DoorEnd.from_json(known["a"]), b=DoorEnd.from_json(known["b"]))


@dataclass(frozen=True, slots=True, kw_only=True)
class Doors:
    """The door graph (data/doors.json, generated by dev-scripts/door-graph.py).

    connections: every mutual door pair, the doors the entrance randomizer shuffles. fixed: (map, destination map)
    links of the doors left out (not a pair the mod can find by map and name); the maps they join count as one area.
    """

    connections: tuple[DoorConnection, ...]
    fixed: tuple[tuple[str, str], ...]

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Doors:
        known = _known(cls, {key: value for key, value in data.items() if key != "_about"})
        return cls(connections=tuple(DoorConnection.from_json(c) for c in known["connections"]),
                   fixed=tuple((a, b) for a, b in known["fixed"]))


@dataclass(frozen=True, slots=True, kw_only=True, order=True)
class RoomStart:
    """A room a random start can begin in, entered as if through the door from from_map."""

    map: str
    from_map: str

    def to_slot(self) -> dict[str, str]:
        return {"map": self.map, "from": self.from_map}


@dataclass(frozen=True, slots=True)
class EntityRef:
    """A map entity the client changes, by name (a scenery entity by its path inside the map); in its area's module.

    kept_open: story blockers kept out of the way, so an area with locations never closes. kept_present: entities the
    story only makes later, made to exist from the start. scenery_hidden and scenery_present: flag-switched scenery
    hidden or shown from the start.
    """

    map: str
    entity: str

    def to_slot(self) -> dict[str, Any]:
        return {"map": self.map, "entity": self.entity}


@dataclass(frozen=True, slots=True)
class FlagEntity:
    """A map entity tied to a story flag instead of, or on top of, its own requirements; in its area's module.

    present_from: made from flag instead of its own requirement. held_until: kept away until flag, on top of its own
    requirements.
    """

    map: str
    entity: str
    flag: int

    def to_slot(self) -> dict[str, Any]:
        return {"map": self.map, "entity": self.entity, "flag": self.flag}


@dataclass(frozen=True, slots=True)
class DialogueFlag:
    """One dialogue line of an entity whose flag is repointed from flag to to (dialogue_flags, in its area's module)."""

    map: str
    entity: str
    flag: int
    to: int

    def to_slot(self) -> dict[str, Any]:
        return {"map": self.map, "entity": self.entity, "flag": self.flag, "to": self.to}


@dataclass(frozen=True, slots=True, kw_only=True)
class SavePoint:
    """A save point (data/starts.json): its map and entity index."""

    map: str
    entity: int

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> SavePoint:
        return cls(**_known(cls, data))


@dataclass(frozen=True, slots=True, kw_only=True)
class Give:
    """The |giveitem,type,item,...| that hands out the vanilla item on that map (type -1 berries, 0 item, 1 key item,
    2 medal): the client keeps it out of the inventory and shows the seed's item instead."""

    map: str
    type: int
    item: int

    def to_slot(self) -> dict[str, Any]:
        return {"map": self.map, "type": self.type, "item": self.item}


@dataclass(frozen=True, slots=True, kw_only=True)
class Pickup:
    """An item lying in the world or buried in a dig spot (type 0 item, 1 key item, 2 medal, 3 crystal berry).

    Its flag (Source.flag) is the pickup's own activationflag. A story pickup (story) has none: it is known by the
    story event it starts (Source.event) and checked by the flag that event sets.
    """

    map: str
    type: int
    item: int
    story: bool = False


@dataclass(frozen=True, slots=True, kw_only=True)
class Added:
    """An item the story puts straight into the bag, with no giveitem (type 0 item, 1 key item): the client leaves it
    out."""

    type: int
    item: int

    def to_slot(self) -> dict[str, Any]:
        return {"type": self.type, "item": self.item}


@dataclass(frozen=True, slots=True, kw_only=True)
class ItemShop:
    """An item shop's slot: its map, keeper and item; its first purchase is the check."""

    map: str
    keeper: str
    item: int

    def to_slot(self) -> dict[str, Any]:
        return {"map": self.map, "keeper": self.keeper, "item": self.item}


@dataclass(frozen=True, slots=True, kw_only=True)
class Source:
    """How the game marks a spot done. Each field is None when the source doesn't have it.

    flag: the global flag the client watches. event: the EventControl event that sets it. npc: the character who gives
    it. give, pickup, added, item_shop: see their records. Instead of a flag: var and at_least (done when
    flagvar[var] reaches at_least; slot_data location_vars), berry (a crystal berry's crystalbflags index;
    location_berries), regional (a respawning pickup's regional flag), discovery (a journal discovery), shop and medal
    (a medal shop's badgeshops index and the medal; one location per copy it ever stocks).
    """

    flag: int | None = None
    event: int | None = None
    npc: str | None = None
    give: Give | None = None
    pickup: Pickup | None = None
    added: Added | None = None
    item_shop: ItemShop | None = None
    var: int | None = None
    at_least: int | None = None
    berry: int | None = None
    regional: int | None = None
    discovery: int | None = None
    shop: int | None = None
    medal: int | None = None

    def present(self) -> set[str]:
        """The fields this source has."""
        return {field.name for field in fields(self) if getattr(self, field.name) is not None}


@dataclass(frozen=True, slots=True)
class DoorRule:
    """A door that is itself a gate (the game makes it only from a story flag): what going through it needs, from its
    own side. The rule is the door's exit's, so it goes with the door wherever the entrance randomizer sends it."""

    map: str
    door: str
    rule: Rule


@dataclass(frozen=True, slots=True)
class Transfer:
    """A way between two maps that isn't a door (a boat, an elevator, a scene), never shuffled. name says what it is;
    two_way: the same way back exists, with the same rule; otherwise it only goes from from_map."""

    name: str
    from_map: str
    to_map: str
    rule: Rule | None = None
    two_way: bool = True


@dataclass(frozen=True, slots=True)
class Location:
    """A location, in its area's module (logic/).

    id is added to LOCATION_ID_BASE and never reused (retired: 4). region: the map it's in, whose region it sits in.
    rule: what the spot itself needs once you're in its map, kept apart from what reaching it needs (so entrance rando
    can change one without the other); written even when reach implies it. reach: what reaching the spot needs beyond
    the doors until its room is mapped (build step 24), the stand-in its area's big region needed. category marks a
    location a yaml option can leave out (quest, crystal_berry, discovery, shop, item_shop; party_member, only with
    Starting Party Member on; story_party, a story event only with it off). quiet marks an opening check whose item
    arrives with no hold-up (the start of a new file). no_jump: seen reachable without a jump (with Shuffle Jump, every
    other spot needs it).
    """

    name: str
    id: int
    region: str
    source: Source
    rule: Rule | None = None
    category: str | None = None
    quiet: bool = False
    no_jump: bool = False
    reach: Rule | None = None


@dataclass(frozen=True, slots=True)
class StoryEvent:
    """A logic-only event (no id): a story step, placed in the map where it happens, whose item other rules require.
    rule, category, no_jump and reach as for a Location."""

    name: str
    item: str
    region: str
    source: Source
    rule: Rule | None = None
    category: str | None = None
    no_jump: bool = False
    reach: Rule | None = None


@dataclass(frozen=True, slots=True)
class Artifact:
    """An artifact, an event (no id): the game counts 7 artifact flags, and the goal is having enough of them. region
    and reach as for a Location."""

    number: int
    name: str
    region: str
    source: Source
    reach: Rule | None = None
