"""Dev-only: every map enemy's encounter from an EntityDump; --export writes data/enemies.json.

One row per enemy entity: map, entity index, the enemy ids it fights (`battleids`), and a respawn timer if any; for
Enemysanity also its area (the map dump's), the first enemy's game name (the enemy table's), the story flags that
bring it and take it away, and its location id, which a re-export keeps (a new enemy gets the next free one).

    python dev-scripts/enemy-table.py <bugfablesap-entitydump.tsv>
    python dev-scripts/enemy-table.py <bugfablesap-entitydump.tsv> --export apworld/bug_fables/data/enemies.json
"""
import collections
import csv
import json
import sys
from pathlib import Path

# A test room, never reached in play.
SKIPPED_MAPS = {"TestRoom"}
# Enemysanity's location ids start here, clear of the hand-written spots.
FIRST_ENEMY_LOCATION = 1000


def flags(text: str) -> list[int]:
    return [int(x) for x in text.split() if x.lstrip("-").isdigit() and int(x) >= 0]


def areas(mapdump: Path) -> dict[str, int]:
    with mapdump.open(encoding="utf-8") as f:
        return {r["map"]: int(r["area"]) for r in csv.DictReader(f, delimiter="	") if r["area"].strip()}


def enemy_names(table: Path) -> dict[int, str]:
    with table.open(encoding="utf-8") as f:
        return {int(r["id"]): r["name"] for r in csv.DictReader(f, delimiter="	")}


def encounters(dump: Path) -> list[dict]:
    folder = dump.parent
    area_of = areas(folder / "bugfablesap-mapdump.tsv")
    names = enemy_names(folder / "bugfablesap-enemies.tsv")
    rows = []
    with dump.open(encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            if r["entitytype"] != "Enemy" or r["map"] in SKIPPED_MAPS:
                continue
            ids = [int(i) for i in r["battleids"].split()]
            if not ids:
                continue
            rows.append({"map": r["map"], "entity": int(r["index"]), "ids": ids,
                         "respawns": r["eventid"].strip() not in ("", "0", "-1"),
                         "area": area_of.get(r["map"], -1), "name": names.get(ids[0], ""),
                         "requires": flags(r["requires"]), "limit": flags(r["limit"])})
    return rows


def keep_location_ids(rows: list[dict], out: Path) -> None:
    """Each enemy keeps the location id it had; a new one gets the next free id."""
    old = json.loads(out.read_text(encoding="utf-8"))["encounters"] if out.exists() else []
    known = {(e["map"], e["entity"]): e["location"] for e in old if "location" in e}
    next_id = max(known.values(), default=FIRST_ENEMY_LOCATION - 1) + 1
    for r in rows:
        r["location"] = known.get((r["map"], r["entity"]))
        if r["location"] is None:
            r["location"] = next_id
            next_id += 1


def main() -> None:
    dump = Path(sys.argv[1])
    out = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[2] == "--export" else None
    rows = encounters(dump)
    if out is None:
        for r in rows:
            print(f'{r["map"]}\t{r["entity"]}\t{" ".join(map(str, r["ids"]))}\t{"respawns" if r["respawns"] else ""}')
        sizes = collections.Counter(len(r["ids"]) for r in rows)
        print(f"# {len(rows)} encounters on {len({r['map'] for r in rows})} maps; sizes {sorted(sizes.items())}",
              file=sys.stderr)
        return
    keep_location_ids(rows, out)
    data = {
        "_about": "Generated by dev-scripts/enemy-table.py --export from the mod's EntityDump; do not edit by hand.",
        "_comment": "encounters: every map enemy (map, entity index) and the enemy ids its fight starts with. "
                    "respawns: a puzzle enemy that comes back after a while (its map model must stay). area, name, "
                    "requires, limit: its map's area, its first enemy's name, the flags that bring it and take it "
                    "away. location: its Enemysanity location id, never reused.",
        "encounters": rows,
    }
    out.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(f"# exported {len(rows)} encounters -> {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
