"""Dev-only: every map enemy's encounter from an EntityDump; --export writes data/enemies.json.

One row per enemy entity: map, entity index, the enemy ids it fights (`battleids`), and a respawn timer if any.

    python dev-scripts/enemy-table.py <bugfablesap-entitydump.tsv>
    python dev-scripts/enemy-table.py <bugfablesap-entitydump.tsv> --export apworld/bug_fables/data/enemies.json
"""
import collections
import csv
import json
import sys
from pathlib import Path

# A test room, never reached in play.
SKIPPED_MAPS = {"TestRoom"}


def encounters(dump: Path) -> list[dict]:
    rows = []
    with dump.open(encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            if r["entitytype"] != "Enemy" or r["map"] in SKIPPED_MAPS:
                continue
            ids = [int(i) for i in r["battleids"].split()]
            if not ids:
                continue
            rows.append({"map": r["map"], "entity": int(r["index"]), "ids": ids,
                         "respawns": r["eventid"].strip() not in ("", "0", "-1")})
    return rows


def main() -> None:
    dump = Path(sys.argv[1])
    out = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[2] == "--export" else None
    rows = encounters(dump)
    if out is None:
        for r in rows:
            print(f'{r["map"]}\t{r["entity"]}\t{" ".join(map(str, r["ids"]))}\t{"respawns" if r["respawns"] else ""}')
        sizes = collections.Counter(len(r["ids"]) for r in rows)
        print(f"# {len(rows)} encounters on {len({r['map'] for r in rows})} maps; sizes {sorted(sizes.items())}",
              file=sys.stderr)
        return
    data = {
        "_about": "Generated by dev-scripts/enemy-table.py --export from the mod's EntityDump; do not edit by hand.",
        "_comment": "encounters: every map enemy (map, entity index) and the enemy ids its fight starts with. "
                    "respawns: a puzzle enemy that comes back after a while (its map model must stay).",
        "encounters": rows,
    }
    out.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")
    print(f"# exported {len(rows)} encounters -> {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
