"""Dev-only: every save point from an EntityDump; --export writes data/starts.json (random start's spots).

One row per save point: map, entity index, and its required / hiding flags (it may only exist in some story states;
the start uses its spot, not the save point itself).

    python dev-scripts/save-points.py <bugfablesap-entitydump.tsv>
    python dev-scripts/save-points.py <bugfablesap-entitydump.tsv> --export apworld/bug_fables/data/starts.json
"""
import csv
import json
import sys
from pathlib import Path

# A test room, never reached in play; copies of an entity carry "Duplicate" in their name.
SKIPPED_MAPS = {"TestRoom"}


def save_points(dump: Path) -> list[dict]:
    rows = []
    with dump.open(encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            if r["objecttype"] != "SavePoint" or r["map"] in SKIPPED_MAPS or "Duplicate" in r["name"]:
                continue
            rows.append({"map": r["map"], "entity": int(r["index"])})
    return rows


def main() -> None:
    dump = Path(sys.argv[1])
    out = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[2] == "--export" else None
    rows = save_points(dump)
    if out is None:
        for r in rows:
            print(f'{r["map"]}\t{r["entity"]}')
        print(f"# {len(rows)} save points", file=sys.stderr)
        return
    data = {
        "_about": "Generated by dev-scripts/save-points.py --export from the mod's EntityDump; do not edit by hand.",
        "_comment": "starts: every save point (map, entity index), the spots a random start picks from.",
        "starts": rows,
    }
    out.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")
    print(f"# exported {len(rows)} save points -> {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
